package com.sipi.groupOne.ui;

import com.sipi.groupOne.BotProject;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import org.jibble.pircbot.User;

public class MainFrame extends javax.swing.JFrame {
    
    private BotProject bot;

    /**
     * Creates new form MainFrame
     *
     * @param bot - BotProject model
     */
    public MainFrame(BotProject bot) {
        initComponents();
        launchGUI.CenteredFrame(this);
        this.setTitle("PircBot : " + bot.getNick() + " @ " + bot.getChannel());
        this.setVisible(true);
        this.bot = bot;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatWindow = new javax.swing.JTextArea();
        disconnectButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        inputText = new javax.swing.JTextField();
        topicTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatWindow.setEditable(false);
        chatWindow.setColumns(20);
        chatWindow.setLineWrap(true);
        chatWindow.setRows(5);
        chatWindow.setWrapStyleWord(true);
        jScrollPane1.setViewportView(chatWindow);

        disconnectButton.setText("Disconnect");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(userList);

        inputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextKeyPressed(evt);
            }
        });

        topicTextField.setEditable(false);
        topicTextField.setText("Channel Topic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addComponent(topicTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disconnectButton)
                    .addComponent(sendButton)
                    .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                bot.disconnect();
                sendButton.setEnabled(false);
                inputText.setText("");
                inputText.setEnabled(false);
            }
        });
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        setChatMessage(bot.getNick(), inputText.getText());
        bot.sendMessage(bot.getChannel(), inputText.getText());
        inputText.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void inputTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.sendButton.doClick();
        }
    }//GEN-LAST:event_inputTextKeyPressed
    
    public void updateUserList() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                User[] users = bot.getUsers(bot.getChannels()[0]);
                SortedListModel slm = new SortedListModel();
                for (User user : users) {
                    slm.add(user.getNick());
                }
                userList.setModel(slm);
            }
        });
        
    }
    
    public void setChatMessage(String user, String msg) {
        String timestamp = new SimpleDateFormat("HH.mm.ss").format(new Date());
        String message = timestamp + " <" + user + "> " + msg + "\n";
        if (chatWindow.getText().isEmpty()) {
            chatWindow.setText(message);
        } else {
            chatWindow.append(message);
        }
        chatWindow.setCaretPosition(chatWindow.getDocument().getLength());
    }
    
    public void setTopic(String channel, String message) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                topicTextField.setText(channel + " - " + message);
            }
        });
        
    }
    
    public void setMessage(String msg) {
        String timestamp = new SimpleDateFormat("HH.mm.ss").format(new Date());
        String message = timestamp + " * " + msg + "\n";
        if (chatWindow.getText().isEmpty()) {
            chatWindow.setText(message);
        } else {
            chatWindow.append(message);
        }
        chatWindow.setCaretPosition(chatWindow.getDocument().getLength());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatWindow;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JTextField inputText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField topicTextField;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
